---
version: "2.1"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CONFIG=ca_montreal,ca_ontario,ca_toronto
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.2.0/24
      - TRANSMISSION_DOWNLOAD_DIR=/completed
      - TRANSMISSION_INCOMPLETE_DIR=/incomplete
      - TRANSMISSION_WATCH_DIR=/watch
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=2000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - ENABLE_UFW=true
      - UFW_ALLOW_GW_NET=true
    volumes:
      - ${DOCKER_FOLDER}/transmission/data:/data
      - ${TORRENT_COMPLETED_FOLDER}:/completed
      - ${TORRENT_INCOMPLETE_FOLDER}:/incomplete
      - ${TORRENT_WATCH_FOLDER}:/watch
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    restart: always
    
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=100
      - VERSION=docker
    ports:
      - 32400:32400
    volumes:
      - ${DOCKER_FOLDER}/plex/config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${TV_SHOWS_FOLDER}:/tvshows
    
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Amercia/Montreal
    volumes:
      - ${DOCKER_FOLDER}/sonarr/config:/config
      - ${TORRENT_COMPLETED_FOLDER}:/torrentcompleted
      - ${TV_SHOWS_FOLDER}:/tvshows
    ports:
      - 8989:8989
    restart: always
    
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
    volumes:
      - ${DOCKER_FOLDER}/radarr/config:/config
      - ${TORRENT_COMPLETED_FOLDER}:/torrentcompleted
      - ${MOVIES_FOLDER}:/movies
    ports:
      - 7878:7878
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
    volumes:
      - ${DOCKER_FOLDER}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=1000
      - PGID=100
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Montreal
    ports:
      - "${PORT:-8191}:8191"
    restart: always
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
    volumes:
      - ${DOCKER_FOLDER}/bazarr/config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${TV_SHOWS_FOLDER}:/tvshows
    ports:
     - 6767:6767
    restart: unless-stopped
